deprecate gazetteer implementation
Dataport/polar pull request #100
Opened 2024-01-30 06:58 UTC by warm-coolguy

## Summary

The gazetteer implementation has been marked as deprecated for the next major release.

## Instructions for local reproduction and review

No relevant changes.

2024-02-02 14:25 UTC, dopenguin requested changes
🏓 @warm-coolguy

2024-02-02 14:25 UTC, dopenguin commented on packages/plugins/AddressSearch/src/utils/searchMethods/getSearchMethod.ts
> +        'Search type "gazetteer" is deprecated. Please use "mpapi" instead.'
```suggestion
        '@polar/plugin-address-search: Search type "gazetteer" is deprecated. Please use "mpapi" instead.'
```

2024-02-05 05:56 UTC, warm-coolguy commented
> 🏓 @warm-coolguy

🏓 @dopenguin

2024-02-05 09:16 UTC, dopenguin approved these changes
🚀 @warm-coolguy

2024-02-05 09:25 UTC, merged