Fix issue of initiallyOpen in @polar/plugin-icon-menu not working
Dataport/polar pull request #123
Opened 2024-04-16 18:24 UTC by dopenguin

## Summary

See the commit for more information.

## Instructions for local reproduction and review

- `npm run meldemichel:dev`
- As configured, the `layerChooser` should be open on start

2024-04-17 05:00 UTC, warm-coolguy requested changes
This is missing a changelog entry.

🏓 @dopenguin

2024-04-17 12:01 UTC, dopenguin commented on packages/plugins/IconMenu/src/store/index.ts
> +        )
Done 2d6a87e6d0f7110dfed2fffc288be2d7d93f78f5

2024-04-17 12:01 UTC, dopenguin commented
> This is missing a changelog entry.
> 
> 🏓 @dopenguin

Added 3c26939e54aaad34dfabc53786ba80284ea17f84

🏓 @warm-coolguy

2024-04-18 05:07 UTC, warm-coolguy approved these changes
🚀 @dopenguin

2024-04-18 07:57 UTC, merged