Feature/add measure tool
Dataport/polar pull request #124
Opened 2024-04-18 07:54 UTC by LDWiegand

## Summary

Added a measure tool for distances and areas

## Instructions for local reproduction and review
npm run snowbox or npm run dataportal

2024-12-30 11:03 UTC, dopenguin commented
@warm-coolguy I've added the relevant parts that were missing here.
However, I've decided against adding a mechanism in `@polar/core` and went with the route we've already established between `@polar/plugin-pins` and `@polar/plugin-draw`.

Let me know if you've got any questions!

2024-12-30 11:04 UTC, dopenguin commented
Also, on another note, I'll tackle the TODOs in `packages/plugins/Measure/src/components/Measure.vue` soon!

2025-01-06 13:10 UTC, warm-coolguy requested changes
🏓 @dopenguin 

After reviewing and summing up my findings I find that an awful lot of my comments is about making this implementation more like `Draw`. A lot of problems we have here have already been solved in `Draw`, and all that progress is lost on this re-implementation and would have to be redone samishly. (After all, `Draw` is the result of a lot of work over a long period of time, and we're on the third-or-so implementation here, learning incrementally.)

This makes me really wonder if `Draw` could just add, by configuration, another radio box section like pseudo-HTML:

```
h3. Measurement
  radio. None
  radio. m, m²
  radio. km, km²
  radio. km, ha
```

When active, lines would show lengths, areas lengths and area, and circles area and maybe circumference or diameter or whatever.

What do you think about this?

2025-01-06 13:10 UTC, warm-coolguy commented on packages/plugins/Measure/src/store/actions/createStyleFunc.ts
> +    },
I don't understand why lines should be fatter when starting a deletion albeit being exactly the elements the user is not supposed to interact with.

2025-01-06 14:05 UTC, dopenguin commented on packages/plugins/Measure/README.md
> +# Measure
Added 9c749c44bf33e4c03875b032cbdb6eab1c30c498

2025-01-06 14:06 UTC, dopenguin commented
> 🏓 @dopenguin
> 
> After reviewing and summing up my findings I find that an awful lot of my comments is about making this implementation more like `Draw`. A lot of problems we have here have already been solved in `Draw`, and all that progress is lost on this re-implementation and would have to be redone samishly. (After all, `Draw` is the result of a lot of work over a long period of time, and we're on the third-or-so implementation here, learning incrementally.)
> 
> This makes me really wonder if `Draw` could just add, by configuration, another radio box section like pseudo-HTML:
> 
> ```
> h3. Measurement
>   radio. None
>   radio. m, m²
>   radio. km, km²
>   radio. km, ha
> ```
> 
> When active, lines would show lengths (and maybe length sum), areas lengths and area, and circles area and maybe circumference or diameter or whatever.
> 
> What do you think about this?

I thought, so far, that that would be an effort we are not taking right now but in the near future. Maybe we should discuss this before this PR gets merged though.

2025-01-06 14:48 UTC, dopenguin commented on packages/plugins/Measure/src/language.ts
> +              'Klicke auf die Ecken einer Messung, um diese zu löschen.\nLinien benötigen mindestens 2, Polygone mindestens 3.',
I've added that as I thought that a user may be confused on how the deletion process works. If you think it is clear enough as is, I can remove it again.

I can add "Ecken" to the second sentence if you want.

The phrasing has been updated 640d5a24c7cbc90393c36e3f68c0d743d608abc6

2025-01-06 14:55 UTC, dopenguin commented on packages/plugins/Measure/src/components/Measure.vue
> +      ></RadioCard>
Adjusted 6a194396bd5444cf9a85aab9b940e7834171ed7f

2025-01-06 15:03 UTC, dopenguin commented on packages/plugins/Measure/src/components/Measure.vue
> +    selectableUnits: () => ({ m: 'm / m²', km: 'km / km²' }),
It was an idea to add here if it doesn't lead to any significant additional time invested.

As far as I can tell, as hectare has no equivalent for length that is supposed to be added, we'd the separation between the selectableUnits for length and those for areas. That is a nice thing anyway, but I am not sure if that is reasonable if we consider merging this plugin with draw in the future.
It also wouldn't be enough to do that here. Changes to the calculation of the area in `packages/plugins/Measure/src/store/actions/createStyleFunc.ts` would be needed as well.

I suggest that we can take another look once we've finished this review.

2025-01-06 15:05 UTC, dopenguin commented on packages/plugins/Measure/src/components/Measure.vue
> +    selectableUnits: () => ({ m: 'm / m²', km: 'km / km²' }),
I moved them out of the store as they are never changed so far. I wanted to add them as `const` in the component, but as far as I can tell, adding them to `data` seems best practice.
So, not sure if we are just disagreeing or if I am missing something. Feel free to 🤙 me!

2025-01-06 15:08 UTC, dopenguin commented on packages/plugins/Measure/src/components/Measure.vue
> +    selectableUnits: () => ({ m: 'm / m²', km: 'km / km²' }),
If we ever support other languages than English and German that will make for an easy change 7efb08ec073ed6761b3f1f3855fe313a2f874c03

2025-01-06 15:10 UTC, dopenguin commented on packages/plugins/Measure/src/components/Measure.vue
> +    },
Forgot to remove this relic 6538e6fda9ae0205aa1c07c280720486814398ae

2025-01-06 15:14 UTC, dopenguin commented on packages/plugins/Measure/src/store/actions/createInteractions.ts
> +      interactions = await dispatch('createDeleteInteraction', drawSource)
Adjusted 8b7258fa8b4b7490ef63d61bc35d69892e4289fe

2025-01-06 15:15 UTC, dopenguin commented on packages/plugins/Measure/src/store/actions/createStyleFunc.ts
> +    },
See https://github.com/Dataport/polar/pull/124#discussion_r1904276897

2025-01-06 15:16 UTC, dopenguin commented on packages/plugins/Measure/src/store/actions/createInteractions.ts
> +  const specialStyle: StyleLike = await dispatch('createStyleFunc', mode)
Renamed 6099fe1ec9135699df794a8891ccc14cf65ed06c

2025-01-06 15:17 UTC, dopenguin commented on packages/plugins/Measure/src/store/actions/createDeleteInteraction/index.ts
> +  }
I thought the implementation added was quite neat and left it as is. But I have no strong feelings and will adjust it.

2025-01-06 15:18 UTC, dopenguin commented on packages/plugins/Measure/src/utils/createStyle.ts
> +      font: 'bold 14px cursive',
Agreed, will add this!

2025-01-06 15:19 UTC, dopenguin commented on packages/plugins/Measure/src/components/Measure.vue
> +    }),
Seems reasonable, will add the configuration possibility!

2025-01-06 15:21 UTC, dopenguin commented on packages/plugins/Measure/src/components/Measure.vue
> +      ></RadioCard>
Adding the area at the center of the polygon seems like a great addition!

2025-01-06 15:22 UTC, dopenguin commented on packages/plugins/Measure/src/store/actions/createInteractions.ts
> +    interactions.push(draw)
Will add the visual indicator to the mouse!

2025-01-06 15:23 UTC, dopenguin commented on packages/plugins/Measure/src/store/actions/createInteractions.ts
> +      interactions = await dispatch('createDeleteInteraction', drawSource)
This should be fixed with the change to https://github.com/Dataport/polar/pull/124#discussion_r1904280396. We can leave the thread open as long as that has not been implemented yet, though.

2025-01-06 15:24 UTC, dopenguin commented on packages/plugins/Measure/src/store/actions/createInteractions.ts
> +      const modify = getModify(drawSource)
Will add that!

2025-01-07 05:42 UTC, warm-coolguy commented on packages/plugins/Measure/src/components/Measure.vue
> +    selectableUnits: () => ({ m: 'm / m²', km: 'km / km²' }),
Pulling length/area units apart seems overly complex to me regarding UI. km should go with ha, so we have m/m², km/km², km/ha.

2025-01-23 16:19 UTC, dopenguin commented on packages/plugins/Measure/src/utils/createStyle.ts
> +      font: 'bold 14px cursive',
Adjusted in the implementation of @polar/plugin-draw

2025-01-23 16:20 UTC, dopenguin commented on packages/plugins/Measure/src/components/Measure.vue
> +    selectableUnits: () => ({ m: 'm / m²', km: 'km / km²' }),
Moved to the store in the implementation of @polar/plugin-draw

2025-01-23 16:20 UTC, dopenguin commented on packages/plugins/Measure/src/components/Measure.vue
> +    }),
No longer relevant in the implementation of @polar/plugin-draw

2025-01-23 16:20 UTC, dopenguin commented on packages/plugins/Measure/src/components/Measure.vue
> +          </v-alert>
No longer relevant in the implementation of @polar/plugin-draw

2025-01-23 16:21 UTC, dopenguin commented on packages/plugins/Measure/src/store/actions/createDeleteInteraction/index.ts
> +      : 3
No longer relevant in the implementation of @polar/plugin-draw

2025-01-23 16:21 UTC, dopenguin commented on packages/plugins/Measure/src/store/actions/createInteractions.ts
> +    interactions.push(draw)
Was not needed to be added as measure is now part of @polar/plugin-draw

2025-01-23 16:21 UTC, dopenguin commented on packages/plugins/Measure/src/store/actions/createInteractions.ts
> +      interactions = await dispatch('createDeleteInteraction', drawSource)
No longer relevant in the implementation of @polar/plugin-draw

2025-01-23 16:21 UTC, dopenguin commented on packages/plugins/Measure/src/store/actions/createInteractions.ts
> +      const modify = getModify(drawSource)
No longer relevant in the implementation of @polar/plugin-draw

2025-01-23 16:22 UTC, dopenguin commented on packages/plugins/Measure/src/store/actions/createDeleteInteraction/index.ts
> +  }
No longer relevant as the implementation moved to @polar/plugin-draw

2025-01-23 16:22 UTC, dopenguin commented on packages/plugins/Measure/src/store/actions/createStyleFunc.ts
> +    },
Styling stays the same in the implementation of @polar/plugin-draw

2025-01-23 16:30 UTC, dopenguin commented
As discussed, I've merged the measure functionality from `@polar/plugin-measure` into `@polar/plugin-draw`.
I've subsequently removed `@polar/plugin-measure` in cdf7047fc93e3c1eaea4dfbb099c2b570f0d63f2 and 24e386ba5b45962ecc56643acf89071dc84f1887

🏓 @warm-coolguy

2025-01-24 08:03 UTC, warm-coolguy requested changes
With https://github.com/Dataport/polar/commit/24e386ba5b45962ecc56643acf89071dc84f1887 gone, there's no documented way on how to subscribe to or otherweise access measurements taken in the map left.

🏓 @dopenguin

2025-01-24 09:23 UTC, dopenguin commented on packages/core/src/index.ts
> +export { RadioCard } from './components'
Last year, in the wake of #108, we had decided to deprecate `@polar/components` and move `MoveHandle.vue` to `@polar/core`. As that branch has not been merged yet, that change is not reflected in the current state.

IMO, having reusable components in either place seems fine. However, I currently lean towards `@polar/core` as that package will always be a part of any client and any plugin can rely that `@polar/core` exists.
On the other hand, it seems fitting to place it in a separate package to be inline with the current architecture and have a better separation of concerns.

I believe it may seem fitting to ☎️ and lay out the pros and cons.

2025-01-27 15:35 UTC, dopenguin commented on packages/plugins/Draw/src/components/Draw.vue
> +        :values="selectableMeasureModes"
Done 037ea04e07feaee9975c7fd6bbaca1c44413104d

2025-01-27 16:16 UTC, dopenguin commented on packages/plugins/Draw/src/utils/createDrawStyle.ts
> +    }
Done a19fbb06f7d10e21a5e3b4356fcfaa8454b0b0fe

2025-01-27 20:44 UTC, dopenguin commented
> With [24e386b](https://github.com/Dataport/polar/commit/24e386ba5b45962ecc56643acf89071dc84f1887) gone, there's no documented way on how to subscribe to or otherweise access measurements taken in the map left.
> 
> 🏓 @dopenguin

I've added the information to the featureCollection cc8de512cf6eaaab972d011a945ba69f20002fda

However, I've encountered an error that stems from the way the draw interaction works and added a todo for that. If you got a lead on how to fix that, let me know. Otherwise, I'll get my thinking cap out 🎩 

🏓 @warm-coolguy

2025-01-28 06:13 UTC, warm-coolguy commented
> > With [24e386b](https://github.com/Dataport/polar/commit/24e386ba5b45962ecc56643acf89071dc84f1887) gone, there's no documented way on how to subscribe to or otherweise access measurements taken in the map left.
> > 🏓 @dopenguin
> 
> I've added the information to the featureCollection [cc8de51](https://github.com/Dataport/polar/commit/cc8de512cf6eaaab972d011a945ba69f20002fda)
> 
> However, I've encountered an error that stems from the way the draw interaction works and added a todo for that. If you got a lead on how to fix that, let me know. Otherwise, I'll get my thinking cap out 🎩
> 
> 🏓 @warm-coolguy

I don't see a simple solution without digging deeper into this. Have you seen the [OL example](https://openlayers.org/en/latest/examples/measure.html)? Maybe there's some indication on how it could be done in another way. (I also kinda like how much simpler the UI is, even though it has less information – do we need per-line measurements?)

I've also noticed an additional bug where, if you draw e.g. a triangle, enter "Edit" mode, and pull from the last corner, a new side will exist that has no measurement on its own.

🏓 @dopenguin

2025-01-28 20:19 UTC, dopenguin commented
> > > With [24e386b](https://github.com/Dataport/polar/commit/24e386ba5b45962ecc56643acf89071dc84f1887) gone, there's no documented way on how to subscribe to or otherweise access measurements taken in the map left.
> > > 🏓 @dopenguin
> > 
> > 
> > I've added the information to the featureCollection [cc8de51](https://github.com/Dataport/polar/commit/cc8de512cf6eaaab972d011a945ba69f20002fda)
> > However, I've encountered an error that stems from the way the draw interaction works and added a todo for that. If you got a lead on how to fix that, let me know. Otherwise, I'll get my thinking cap out 🎩
> > 🏓 @warm-coolguy
> 
> I don't see a simple solution without digging deeper into this. Have you seen the [OL example](https://openlayers.org/en/latest/examples/measure.html)? Maybe there's some indication on how it could be done in another way. (I also kinda like how much simpler the UI is, even though it has less information – do we need per-line measurements?)
> 
> I've also noticed an additional bug where, if you draw e.g. a triangle, enter "Edit" mode, and pull from the last corner, a new side will exist that has no measurement on its own.
> 
> 🏓 @dopenguin

After further digging it concluded that the issue exists because of the fix for modifying snapped features in `packages/plugins/Draw/src/store/createInteractions/createModifyInteractions.ts`.
This probably doesn't work because there are multiple `dragSegments` that need to be modified to be able to modify a Polygon.

I tested multiple different scenarious to change the underlying `Collection` when [`modifystart`](https://openlayers.org/en/v9.2.4/apidoc/module-ol_interaction_Modify.ModifyEvent.html#event:modifystart) is called. This either involved directly changing `event.features` or changing `event.target.features_`.
Somehow, changing either of those to only include one feature by a) setting the whole `Collection` to be new or b) updating the `Collection` via the provided methods didn't yield *any* results; all snapped features where still being modified.

When checking how OpenLayers handles this, [one example](https://openlayers.org/en/v9.2.4/examples/draw-and-modify-features.html) includes the same issue of not being able to un-snap features while [another example](https://openlayers.org/en/latest/examples/snap.html) fixes this by using a `Select` interaction to be the base for the features that can be modified.

All in all, this outcome does not seem satifying whatsoever. However, I suggest that we go the route of the second example and use a `Select` interaction for the whole modification process (not only for text). This is not the best solution UX-wise, but at least it is consistent.

I'd like to tackle this **NOT** as part of this PR as this issue is not new but only has become clear now. We'd also be able to merge #211. 
I'll create an issue to change the modification process to work based on a `Select` interaction and assign it to myself if you agree.

2025-01-29 15:04 UTC, merged