Add basic tests for the store of @polar/plugin-icon-menu
Dataport/polar pull request #126
Opened 2024-04-19 18:48 UTC by dopenguin

## Summary

Add tests for the actions of `@polar/plugin-icon-menu`.

## Instructions for local reproduction and review

`npm run test`

2024-04-30 04:18 UTC, warm-coolguy requested changes
🏓 @dopenguin

2024-04-30 04:18 UTC, warm-coolguy commented on packages/plugins/IconMenu/tests/store.spec.ts
> +        })
This test seems to be identical to the previous test `should do nothing if the menu with the given id is not configured`. Probably a copypaste leftover?

2024-05-06 16:14 UTC, dopenguin commented
> 🏓 @dopenguin

🏓 @warm-coolguy

2024-05-27 09:27 UTC, warm-coolguy approved these changes
>> 🏓 @dopenguin
>>
>🏓 @warm-coolguy 
>

🚀 @dopenguin

2024-05-27 14:20 UTC, merged