Fix/remove unused props and attributes
Dataport/polar pull request #131
Opened 2024-05-06 14:22 UTC by dopenguin

## Summary

Removed unused or redundant props, removed orphaned configuration parameters and adjusted documentation and types to properly reflect optionality while also adding all configurable parameters to the documentation. 
For more information, take a look at the respective changelogs.

## Instructions for local reproduction and review

DISH, Meldemichel and snowbox have been updated. All changes are non-breaking, thus the behaviour shouldn't have changed.

2024-05-30 06:27 UTC, warm-coolguy requested changes
🏓 @dopenguin

2024-05-31 15:43 UTC, dopenguin commented on packages/clients/dish/CHANGELOG.md
> +- Refactor: Adjust dish-gfi-component to the new API.
Agreed 57dae6e73f7faef4896361a35fdd274c467ac168

2024-05-31 15:43 UTC, dopenguin commented on packages/clients/meldemichel/CHANGELOG.md
> +- Refactor: Adjust meldemichel-gfi-component to the new API.
Agreed 57dae6e73f7faef4896361a35fdd274c467ac168

2024-05-31 15:43 UTC, dopenguin commented on packages/plugins/Gfi/README.md
> -> ⚠️ The display feature is currently not meant for production. Please use data bindings for display to avoid obstructing the map client.
Added that to the agenda

2024-05-31 15:45 UTC, dopenguin commented on packages/lib/getFeatures/types.ts
> +  xmlns: string
It is first sorted by required and optional parameters, then alphabetically.

2024-05-31 15:46 UTC, dopenguin commented
> 🏓 @dopenguin

🏓 @warm-coolguy 

We can further work on this PR after the next weekly.

2024-06-27 08:32 UTC, dopenguin commented on packages/plugins/Gfi/README.md
> -> ⚠️ The display feature is currently not meant for production. Please use data bindings for display to avoid obstructing the map client.
Re-added the information cb5febcbe74f1c82a3002c459da9cd60c891f9a6

2024-06-27 08:32 UTC, dopenguin commented
> > 🏓 @dopenguin
> 
> 🏓 @warm-coolguy
> 
> We can further work on this PR after the next weekly.

🏓 @warm-coolguy

2024-06-27 08:50 UTC, warm-coolguy approved these changes
> > > 🏓 @dopenguin
> > 
> > 
> > 🏓 @warm-coolguy
> > We can further work on this PR after the next weekly.
> 
> 🏓 @warm-coolguy

🚀 @dopenguin

2024-06-27 08:51 UTC, merged