POLAR-362 Update deprecated boolean of movable parameter to enum value
Dataport/polar pull request #148
Opened 2024-07-30 12:27 UTC by Softwarecules

## Summary

Use of `movable` with `boolean` has been deprecated - The client configs and the examples have been updated to reflect this and now use an enum value as default.

## Instructions for local reproduction and review
Run the examples for `dish`, `afm` and `meldemichel` respectively and examine the pin-behaviour. It should work as intended and be dragable.

## Relevant tickets, issues, et cetera
https://github.com/Dataport/polar/issues/145 
https://jira.dataport.de/browse/POLAR-362

2024-07-30 18:06 UTC, dopenguin requested changes
Added a required change to the README.md and also suggested some slight adjustments for the changelog entries.

🏓 @Softwarecules

2024-07-30 18:06 UTC, dopenguin commented on packages/plugins/Pins/README.md
> +| movable          | 'drag' \| 'click' \| 'none' | Whether a user may drag and re-click the pin (`drag` or `true`), only re-click it (`click`) or may only be placed programmatically (`none` or `false
```suggestion
| movable          | boolean \| 'drag' \| 'click' \| 'none'? | Whether a user may drag and re-click the pin (`drag` or `true`), only re-click it (`click`) or may only be placed programmatically (`none` or `false`). Defaults to 'none'. **Using a boolean for this configuration has been deprecated and will be removed in the next major release.**           |
```
The boolean should still be present, as it is still a valid configuration as of now.  
I also moved the `?` (indicator for optionality) to the end.

2024-07-31 08:35 UTC, Softwarecules commented
> Added a required change to the README.md and also suggested some slight adjustments for the changelog entries.
> 
> 🏓 @Softwarecules

Applied the suggested changes :) 
🏓 @dopenguin

2024-07-31 09:34 UTC, dopenguin reviewed
Approve inbound as soon as #147 has been merged to main @Softwarecules

2024-07-31 11:45 UTC, Softwarecules commented
> Approve inbound as soon as #147 has been merged to main @Softwarecules

@dopenguin #147 merged 🫡

2024-07-31 13:08 UTC, dopenguin approved these changes
🚀 @Softwarecules

2024-07-31 13:16 UTC, merged