Update readme files regarding reference on global plugin parameters
Dataport/polar pull request #152
Opened 2024-07-31 14:27 UTC by Softwarecules

## Summary

Updated the plugin.fields part of the @polar/core documentation to make it easier to understand and navigate. Also added a reference to the global parameters part in every plugin documentation in the configuration section.

## Instructions for local reproduction and review
Check the `README.md` files.

## Relevant tickets, issues, et cetera

2024-07-31 16:21 UTC, dopenguin commented
I've also realized that the links won't be working on the online documentation for the clients (e.g https://dataport.github.io/polar/docs/afm/plugin-draw.html)

My guess would be that the file `scripts/makeDocs.js` needs an adjustment that replaces the relative path with a link to the correct place of the documentation relevant for the client

2024-08-01 04:47 UTC, Softwarecules commented on packages/plugins/Export/README.md
>  To remove user control, add `displayComponent: false` to the configuration and use the following interactions.
Hmm I don't understand this one 🤔 Above the new line? What do you mean?

2024-08-01 08:31 UTC, dopenguin commented on packages/plugins/Export/README.md
>  To remove user control, add `displayComponent: false` to the configuration and use the following interactions.
The sentence `To remove user control, add `displayComponent: false` to the configuration and use the following interactions.` should be adjusted and placed above the new sentence `For details on the `displayComponent` attribute, refer to the [Global Plugin Parameters](../../core/README.md#global-plugin-parameters) section of `@polar/core`.`

2024-08-05 06:43 UTC, Softwarecules commented on packages/plugins/ReverseGeocoder/README.md
> +
FIxed 👍

2024-08-05 06:43 UTC, Softwarecules commented on packages/plugins/Export/README.md
>  To remove user control, add `displayComponent: false` to the configuration and use the following interactions.
FIxed 👍 ``

2024-08-05 06:43 UTC, Softwarecules commented on packages/plugins/Pins/README.md
> +
FIxed 👍

2024-08-05 08:23 UTC, dopenguin requested changes
Merging the `defaultOptions` in `@polar/client-snowbox` is not relevant as well.

Looks good otherwise 🏓 @Softwarecules

2024-08-05 08:23 UTC, dopenguin commented on packages/clients/meldemichel/CHANGELOG.md
> +- Chore: Removed the `displayComponent` attribute for `@polar/plugin-pins` as it is not necessary.
```suggestion
```
Not relevant for the consumer of this client

2024-08-07 12:58 UTC, dopenguin requested changes
> > Merging the `defaultOptions` in `@polar/client-snowbox` is not relevant as well.
> > Looks good otherwise 🏓 @Softwarecules
> 
> I don't really understand what you mean by this^^ I didn't touch the `defaultOptions`? Otherwise I am done now @dopenguin 🏓

The `defaultOptions` are merged in for `Pins` in `@polar/client-snowbox`. This is not be needed and should be changed while we are at it.

I've added two suggestions which for the MarkDown file but not for the resulting html (the headings are missing ids, see [here](https://developers.google.com/style/headings-targets)).

🏓 @Softwarecules

2024-08-07 12:58 UTC, dopenguin commented on packages/core/README.md
> +| <plugin.fields> | various? | Fields for configuring plugins added with `addPlugins`. Refer to each plugin's documentation for specific fields and options. Global plugin parameters are described [be
```suggestion
| <plugin.fields> | various? | Fields for configuring plugins added with `addPlugins`. Refer to each plugin's documentation for specific fields and options. Global plugin parameters are described [below](#global-plugin-parameters). |
```

2024-08-07 12:58 UTC, dopenguin commented on packages/core/README.md
> +Plugins in POLAR are modular components that extend the functionality of the map client. They can be added using the [addPlugins](../core/README.md#addPlugins) method and configured through the `mapC
```suggestion
Plugins in POLAR are modular components that extend the functionality of the map client. They can be added using the [addPlugins](#addPlugins) method and configured through the `mapConfiguration` object. Each plugin has its own set of fields and options that can be customized.
```

2024-08-07 13:44 UTC, dopenguin approved these changes
🚀 @Softwarecules

2024-08-07 14:07 UTC, merged