Chore/upgrade lerna
Dataport/polar pull request #153
Opened 2024-08-01 11:55 UTC by dopenguin

## Summary

Use `nx` with `npm workspaces` instead of `lerna`.

## Instructions for local reproduction and review

- `npm i`
- e.g. `npm run meldemichel:dev`
- e.g. `npm run meldemichel:build` 

## Relevant tickets, issues, et cetera

#149 has to be merged before this

2024-09-06 07:28 UTC, dopenguin commented
@warm-coolguy as mentioned in the PR description, the `makeDocs` script uses the versions of the packages located in the repository.
Do you deem that an issue and should we address that regarding differing versions of the clients? Or should simply we always try to keep the clients in sync with the current versions we are developing (which I'm favouring)

2024-09-10 11:10 UTC, warm-coolguy requested changes
Running `npm run pages:build && npm run pages:build:serve` will provide no contents for `http://127.0.0.1:8080/docs/snowbox/client-snowbox.html`, and the folder `pages/docs/snowbox` is actually empty.

🏓 @dopenguin

2024-09-10 13:35 UTC, dopenguin commented on package.json
> +    "@types/node": "^20.14.8",
Good catch! Adjusted it 40e72e469398542bcd02621880a949b853a7fd2e

2024-09-12 18:55 UTC, dopenguin commented
> Running `npm run pages:build && npm run pages:build:serve` will provide no contents for `http://127.0.0.1:8080/docs/snowbox/client-snowbox.html`, and the folder `pages/docs/snowbox` is actually empty.
> 
> > @warm-coolguy as mentioned in the PR description, the makeDocs script uses the versions of the packages located in the repository.
> > Do you deem that an issue and should we address that regarding differing versions of the clients? Or should simply we always try to keep the clients in sync with the current versions we are developing (which I'm favouring)
> 
> That is an issue as soon as we have a client where `^` doesn't suffice to update to the newest version, and since some breaking change releases are planned, that is pretty much imminent. Where does `nx` put those 'old' dependencies, right in the clients? In that case, the solution could be a rather small piece of fallback logic.
> 
> 🏓 @dopenguin

I've fixed the issue you've encountered; `snowbox` was the only client having `@polar`-dependencies as `dependencies` instead of `devDependencies`.

`nx` doesn't handle that, `npm workspaces` does that. I suppose those dependencies would be put in the `node_modules`-folder of the client itself, like you expect.
Do you see that as a change for this PR or something we can take a look at once we release the new major versions?

🏓 @warm-coolguy

2024-09-13 04:57 UTC, warm-coolguy approved these changes
> `nx` doesn't handle that, `npm workspaces` does that. I suppose those dependencies would be put in the `node_modules`-folder of the client itself, like you expect. Do you see that as a change for this PR or something we can take a look at once we release the new major versions?
> 
> 🏓 @warm-coolguy

Sure, we can delegate that to future us. But we'll have to be a little clever about it, or else we'll break the repository right on `main`. I guess there's some local publishing to do. 🤔 We'll see.

🚀 @dopenguin

2024-09-13 09:29 UTC, merged