Feature/e2e tests poc
Dataport/polar pull request #187
Opened 2024-09-19 10:47 UTC by warm-coolguy

## Summary

Added playwright as E2E framework with rather trivial example test. With this, we can test some "big picture" effects.

## Instructions for local reproduction and review

`npm i`, `npx playwright install` to install browsers for your system once (from what I understand, this has to be done once per executing machine), `npm run test:e2e`.

2024-09-23 13:30 UTC, dopenguin commented
The pipeline for the E2E tests are currently failing. 🏓 me, once the lights are green!

2024-09-26 11:54 UTC, warm-coolguy commented
> The pipeline for the E2E tests are currently failing. 🏓 me, once the lights are green!

🏓 @dopenguin 

Also added another test to display canvas interaction possibilities.

2024-09-30 09:23 UTC, dopenguin requested changes
🏓 @warm-coolguy

2024-09-30 09:24 UTC, warm-coolguy commented on .gitignore
> +node_modules/
Yep, removed it.

2024-09-30 09:27 UTC, warm-coolguy commented on playwright.config.ts
We deleted some lines on the telephonator. ☎️

2024-09-30 09:29 UTC, warm-coolguy commented
> 🏓 @warm-coolguy

🏓 @dopenguin

2024-09-30 09:30 UTC, dopenguin approved these changes
🚀 @warm-coolguy

2024-09-30 09:30 UTC, merged