Fix issue regarding not being able to separately modify snapped features
Dataport/polar pull request #192
Opened 2024-09-30 12:40 UTC by dopenguin

## Summary

Fixed the issue of multiple features being permanently snapped together.
I don't really like the fix, as it uses internal features of OpenLayers (here, `dragSegments`). This might break on any version update of OpenLayers. The alternative would be to go over the `Select`-interaction, meaning a non-immediate Modify.

## Instructions for local reproduction and review

`npm run snowbox` and test all the different situations of drawing features.

2024-10-01 04:51 UTC, warm-coolguy requested changes
🏓 @dopenguin I propose you add an E2E test so we immediately know when it breaks. I consider your solution elegant, btw. Additional select interactions are quite the hassle and we'll usually not have situations with overlapping features anyway, so arbitrary interaction should be the minimal interference with usability.

2024-11-14 15:42 UTC, dopenguin commented
> 🏓 @dopenguin I propose you add an E2E test so we immediately know when it breaks. I consider your solution elegant, btw. Additional select interactions are quite the hassle and we'll usually not have situations with overlapping features anyway, so arbitrary interaction should be the minimal interference with usability.

🏓 @warm-coolguy Added the requested E2E test that tests this.

2024-11-18 06:17 UTC, warm-coolguy commented
> > 🏓 @dopenguin I propose you add an E2E test so we immediately know when it breaks. I consider your solution elegant, btw. Additional select interactions are quite the hassle and we'll usually not have situations with overlapping features anyway, so arbitrary interaction should be the minimal interference with usability.
> 
> 🏓 @warm-coolguy Added the requested E2E test that tests this.

🏓 @dopenguin 

The test fails in both Chromium and Firefox on Windows with:

```
  1) [firefox] › draw.spec.ts:44:5 › two features drawn at the same coordinate can be modified separately 

    Error: expect(received).not.toBe(expected) // Object.is equality

    Expected: not 566508.9996571002
```

2024-11-18 08:24 UTC, dopenguin commented
> > > 🏓 @dopenguin I propose you add an E2E test so we immediately know when it breaks. I consider your solution elegant, btw. Additional select interactions are quite the hassle and we'll usually not have situations with overlapping features anyway, so arbitrary interaction should be the minimal interference with usability.
> > 
> > 
> > 🏓 @warm-coolguy Added the requested E2E test that tests this.
> 
> 🏓 @dopenguin
> 
> The test fails in both Chromium and Firefox on Windows with:
> 
> ```
>   1) [firefox] › draw.spec.ts:44:5 › two features drawn at the same coordinate can be modified separately 
> 
>     Error: expect(received).not.toBe(expected) // Object.is equality
> 
>     Expected: not 566508.9996571002
> ```

It works in the pipeline though 🤔 
I can not run E2E tests at all on my machine, would you go with "pipeline is the truth"?
🏓 @warm-coolguy

2024-11-18 08:36 UTC, warm-coolguy commented
> > > > 🏓 @dopenguin I propose you add an E2E test so we immediately know when it breaks. I consider your solution elegant, btw. Additional select interactions are quite the hassle and we'll usually not have situations with overlapping features anyway, so arbitrary interaction should be the minimal interference with usability.
> > > 
> > > 
> > > 🏓 @warm-coolguy Added the requested E2E test that tests this.
> > 
> > 
> > 🏓 @dopenguin
> > The test fails in both Chromium and Firefox on Windows with:
> > ```
> >   1) [firefox] › draw.spec.ts:44:5 › two features drawn at the same coordinate can be modified separately 
> > 
> >     Error: expect(received).not.toBe(expected) // Object.is equality
> > 
> >     Expected: not 566508.9996571002
> > ```
> 
> It works in the pipeline though 🤔 I can not run E2E tests at all on my machine, would you go with "pipeline is the truth"? 🏓 @warm-coolguy

NOTE: We talked separately and decided I'll look into this eventually. It may take some time until I come around to this.

2025-01-06 09:00 UTC, warm-coolguy approved these changes
> > > > > 🏓 @dopenguin I propose you add an E2E test so we immediately know when it breaks. I consider your solution elegant, btw. Additional select interactions are quite the hassle and we'll usually not have situations with overlapping features anyway, so arbitrary interaction should be the minimal interference with usability.
> > > > 
> > > > 
> > > > 🏓 @warm-coolguy Added the requested E2E test that tests this.
> > > 
> > > 
> > > 🏓 @dopenguin
> > > The test fails in both Chromium and Firefox on Windows with:
> > > ```
> > >   1) [firefox] › draw.spec.ts:44:5 › two features drawn at the same coordinate can be modified separately 
> > > 
> > >     Error: expect(received).not.toBe(expected) // Object.is equality
> > > 
> > >     Expected: not 566508.9996571002
> > > ```
> > 
> > It works in the pipeline though 🤔 I can not run E2E tests at all on my machine, would you go with "pipeline is the truth"? 🏓 @warm-coolguy
> 
> NOTE: We talked separately and decided I'll look into this eventually. It may take some time until I come around to this.

🚀 @dopenguin 

It turns out that this error was not, as I expected, specific to Windows, but specific to "I rebuildn't the Snowbox so the changes weren't present in my test.". Which is somewhat annoying to do manually, but a fault on my end. Approved.

2025-01-06 09:01 UTC, merged