Fix/text locator heatmap
Dataport/polar pull request #195
Opened 2024-10-01 12:24 UTC by warm-coolguy

## Summary

- Fix the Heatmap feature. When selecting literature with multiple geometries, they can now be displayed as heatmap again.
- Removed a false warning.

## Instructions for local reproduction and review

Run TextLocator, search for "TODO FILL OUT WHAT TO SEARCH FOR FOR A GOOD EXAMPLE", and test the heatmap functionality on it.

## Relevant tickets, issues, et cetera

Blocks on https://github.com/Dataport/polar/pull/172

2024-11-07 09:28 UTC, dopenguin requested changes
🏓 @warm-coolguy 
Also, a changelog is missing

2024-11-07 09:28 UTC, dopenguin commented on packages/clients/textLocator/src/plugins/GeometrySearch/utils/vectorDisplay.ts
> +  console.error('locationFrequency', locationFrequency)
```suggestion
```

2024-11-07 09:28 UTC, dopenguin commented on packages/clients/textLocator/src/plugins/GeometrySearch/utils/vectorDisplay.ts
> +  console.error('mäx', max)
```suggestion
```

2024-11-08 05:39 UTC, warm-coolguy commented
> 🏓 @warm-coolguy Also, a changelog is missing

🏓 @dopenguin The situation has been resolved by providing a changelog entry matching the implementation. https://github.com/Dataport/polar/pull/195/commits/8f54246843b2320bbc7f8a3cc8404d54b3c1502e

2024-11-08 14:17 UTC, dopenguin approved these changes
🚀  @warm-coolguy 

Also added a suggestion as I prefer imperative in changelogs

2024-11-08 14:17 UTC, dopenguin commented on packages/clients/textLocator/CHANGELOG.md
> +- Fix: The heatmap feature has been adjusted to match the new data structure and works again.
```suggestion
- Fix: Adjust heatmap feature to match the new data structure and have it working again.
```

2024-11-18 06:06 UTC, merged