Feature/gfi multiple features
Dataport/polar pull request #201
Opened 2024-11-07 09:09 UTC by dopenguin

## Summary

Add the configuration parameters `directSelect` and `multiSelect` to be able to select multiple features.

## Instructions for local reproduction and review

`npm run snowbox` and use a modifier key to drag and select multiple. If you drag across a selected value, it gets deselected. If you configure `directSelect`, it should work the same. Beware the information in the readme though.

2024-11-08 06:50 UTC, warm-coolguy requested changes
🏓 @dopenguin

2024-11-08 14:48 UTC, dopenguin commented on packages/plugins/Gfi/src/store/actions/debouncedGfiRequest.ts
> +            }, oldSelection[layerId] as GeoJsonFeature[])
My guess would've been that 

```ts
Array.from(
  new Set(features).symmetricDifference(
    new Set(oldSelection[layerId])
  )
)
```

would've worked, but it just leads to the situation that everything gets added, constantly.  
My guess would be that `symmetricDifference` can not compare the features properly.

2024-11-08 14:53 UTC, dopenguin commented on packages/plugins/Gfi/src/store/actions/index.ts
> +    setupMultiSelection({ dispatch, getters, rootGetters }) {
Agreed and adjusted da374f2a68c1e0f85757e03ff1788b0346ab6c34

2024-11-08 14:54 UTC, dopenguin commented
> 🏓 @dopenguin

🏓 @warm-coolguy

2024-11-18 06:28 UTC, warm-coolguy commented on packages/plugins/Gfi/src/store/actions/debouncedGfiRequest.ts
> +            }, oldSelection[layerId] as GeoJsonFeature[])
Revisiting this, I've realized the comparison only works by the features' properties. So we're probably looking at copies, which would explain why `symmetricDifference` does not work.

I wonder whether that's a problem for a general solution. On the one hand, our use cases will probably always be distinguishable by their properties. On the other, we may have ids or even [foreign members](https://datatracker.ietf.org/doc/html/rfc7946#section-6.1) (had to look this up myself ...) as distinguishing elements.

Hence I'd propose we at least document that feature ought to be distinguishable by their properties for the functionality to work, and, if it ever becomes a problems, revisit this.

2024-11-18 08:09 UTC, warm-coolguy commented
> > 🏓 @dopenguin
> 
> 🏓 @warm-coolguy

🏓 @dopenguin

2024-11-18 08:22 UTC, dopenguin commented on packages/plugins/Gfi/src/store/actions/debouncedGfiRequest.ts
> +            }, oldSelection[layerId] as GeoJsonFeature[])
Added a relevant comment to the documentation d4a0d109c4ee5f814a3a8911df1d28a0451b6e5f

2024-11-18 08:24 UTC, merged