enhance README
Dataport/polar pull request #22
Opened 2023-11-16 12:38 UTC by warm-coolguy

## Summary

Extend README by plugin list and more detailed "getting started" instructions depending on user role.

## Instructions for local reproduction and review

View the file.

2023-11-16 18:14 UTC, dopenguin requested changes
Just some rough suggestions but looks really cool overall!

🏓 @warm-coolguy

2023-11-16 18:14 UTC, dopenguin commented on README.md
> +|[AddressSearch](https://github.com/Dataport/polar/tree/main/packages/plugins/AddressSearch)|Offers a search field and standard search service implementations with API for your own configurable custo
```suggestion
|[AddressSearch](https://github.com/Dataport/polar/tree/main/packages/plugins/AddressSearch)|Offers a search field and standard search service implementations with API for your own configurable custom search services. For already usable search services, see the documentation of the package. Integration with Reverse Geocoder and Pins possible, or usable as a data source for further processing.|
```
Or something along those lines :D

2023-11-16 18:14 UTC, dopenguin commented on README.md
> +Select a client from our [releases](https://github.com/Dataport/polar/releases). For a generic client, use a `@polar/client-afm`. The zipped client is downloadable and attached as an asset to the rel
```suggestion
Select a client from our [releases](https://github.com/Dataport/polar/releases). For a generic client, use `@polar/client-afm`. The zipped client is downloadable and attached as an asset to the release.
```

2023-11-16 18:14 UTC, dopenguin commented on README.md
> +The package contains example files that illustrate how the client can be used. You may also inspect the usage [here](https://github.com/Dataport/polar/tree/main/packages/clients/afm/example).
```suggestion
The package contains example files that illustrate how the client can be used. You may also the example usage [here](https://github.com/Dataport/polar/tree/main/packages/clients/afm/example).
```

2023-11-17 07:45 UTC, warm-coolguy commented on README.md
> +The package contains example files that illustrate how the client can be used. You may also inspect the usage [here](https://github.com/Dataport/polar/tree/main/packages/clients/afm/example).
You may also the verb.

2023-11-17 07:52 UTC, warm-coolguy commented
> 🏓 @warm-coolguy

🏓 @dopenguin quick

2023-11-17 08:54 UTC, dopenguin approved these changes
🚀 @warm-coolguy

2023-11-17 09:12 UTC, merged