Update attributions position in Meldemichel
Dataport/polar pull request #57
Opened 2023-12-13 14:46 UTC by dopenguin

## Summary

- The attributions are being rendered independently again to indicate its secondary nature.
- Fix the alignment of the Scales on narrow devices.

## Instructions for local reproduction and review

Run meldemichel and check whether the information is properly displayed.

2023-12-14 06:40 UTC, warm-coolguy requested changes
🏓 @dopenguin

2023-12-14 06:40 UTC, warm-coolguy commented on packages/clients/meldemichel/src/addPlugins.ts
The attributions can't be read on mobile devices in landscape mode.

![underlap](https://github.com/Dataport/polar/assets/108349707/0c6cf5c1-13d9-41f7-944b-557c20a73e68)

2023-12-20 14:19 UTC, dopenguin commented on packages/clients/meldemichel/src/addPlugins.ts
Fixed e1a45aaf

2023-12-20 14:21 UTC, dopenguin commented
> 🏓 @dopenguin

🏓 @warm-coolguy

2023-12-21 05:38 UTC, warm-coolguy commented on packages/clients/meldemichel/src/addPlugins.ts
The solution is insufficient on e.g. my Galaxy A12. I don't think a width-related solution is appropriate.

2023-12-21 05:38 UTC, warm-coolguy commented
> > 🏓 @dopenguin
> 
> 🏓 @warm-coolguy

🏓 @dopenguin

2023-12-21 08:19 UTC, dopenguin commented on packages/clients/meldemichel/src/addPlugins.ts
Oh, that might be a result of the order in `addPlugins`! I'll take a look into that

2023-12-21 10:50 UTC, dopenguin commented on packages/clients/meldemichel/src/addPlugins.ts
Added a `z-index` to the attributions c2af7cf7

2023-12-21 10:51 UTC, dopenguin commented
> > > 🏓 @dopenguin
> > 
> > 
> > 🏓 @warm-coolguy
> 
> 🏓 @dopenguin

🏓 @warm-coolguy

2023-12-22 06:08 UTC, warm-coolguy commented on packages/clients/meldemichel/src/addPlugins.ts
Seems like `z-index` is also the root issue here since AddressSearch does have it set to `1`. I guess we're fighting fire with fire then.

What about the changes of https://github.com/Dataport/polar/commit/e1a45aaffc27923b6e0b147c907f608392208d8e? Do they still serve a purpose, or should they be reverted? Where did that width come from and was it intentional?

2023-12-22 06:09 UTC, warm-coolguy commented
> > > > 🏓 @dopenguin
> > > 
> > > 
> > > 🏓 @warm-coolguy
> > 
> > 
> > 🏓 @dopenguin
> 
> 🏓 @warm-coolguy

🏓 @dopenguin

2023-12-22 12:32 UTC, dopenguin commented on packages/clients/meldemichel/src/addPlugins.ts
I'll try to use some water on the addressSearch then

The changes can be reverted, not sure why the `windowWidth` has been set differently

2023-12-22 12:40 UTC, dopenguin commented
> > > > > 🏓 @dopenguin
> > > > 
> > > > 
> > > > 🏓 @warm-coolguy
> > > 
> > > 
> > > 🏓 @dopenguin
> > 
> > 
> > 🏓 @warm-coolguy
> 
> 🏓 @dopenguin

🏓 @warm-coolguy

2024-01-02 07:20 UTC, warm-coolguy approved these changes
> > > > > > 🏓 @dopenguin
> > > > > 
> > > > > 
> > > > > 🏓 @warm-coolguy
> > > > 
> > > > 
> > > > 🏓 @dopenguin
> > > 
> > > 
> > > 🏓 @warm-coolguy
> > 
> > 🏓 @dopenguin
> 
> 🏓 @warm-coolguy 

🚀 @dopenguin

2024-01-02 11:19 UTC, merged